# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: osi3/osi_referenceline.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'osi3/osi_referenceline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from osi3 import osi_common_pb2 as osi3_dot_osi__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cosi3/osi_referenceline.proto\x12\x04osi3\x1a\x15osi3/osi_common.proto\"\xba\x01\n\rReferenceLine\x12\x1c\n\x02id\x18\x01 \x01(\x0b\x32\x10.osi3.Identifier\x12\x39\n\tpoly_line\x18\x02 \x03(\x0b\x32&.osi3.ReferenceLine.ReferenceLinePoint\x1aP\n\x12ReferenceLinePoint\x12&\n\x0eworld_position\x18\x01 \x01(\x0b\x32\x0e.osi3.Vector3d\x12\x12\n\ns_position\x18\x02 \x01(\x01\x42\x02H\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osi3.osi_referenceline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\001'
  _globals['_REFERENCELINE']._serialized_start=62
  _globals['_REFERENCELINE']._serialized_end=248
  _globals['_REFERENCELINE_REFERENCELINEPOINT']._serialized_start=168
  _globals['_REFERENCELINE_REFERENCELINEPOINT']._serialized_end=248
# @@protoc_insertion_point(module_scope)
