# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: osi3/osi_detectedlane.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'osi3/osi_detectedlane.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from osi3 import osi_lane_pb2 as osi3_dot_osi__lane__pb2
from osi3 import osi_detectedobject_pb2 as osi3_dot_osi__detectedobject__pb2
from osi3 import osi_common_pb2 as osi3_dot_osi__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bosi3/osi_detectedlane.proto\x12\x04osi3\x1a\x13osi3/osi_lane.proto\x1a\x1dosi3/osi_detectedobject.proto\x1a\x15osi3/osi_common.proto\"\xc6\x01\n\x0c\x44\x65tectedLane\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.osi3.DetectedItemHeader\x12\x33\n\tcandidate\x18\x02 \x03(\x0b\x32 .osi3.DetectedLane.CandidateLane\x1aW\n\rCandidateLane\x12\x13\n\x0bprobability\x18\x01 \x01(\x01\x12\x31\n\x0e\x63lassification\x18\x02 \x01(\x0b\x32\x19.osi3.Lane.Classification\"\xbb\x03\n\x14\x44\x65tectedLaneBoundary\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.osi3.DetectedItemHeader\x12\x43\n\tcandidate\x18\x02 \x03(\x0b\x32\x30.osi3.DetectedLaneBoundary.CandidateLaneBoundary\x12\x37\n\rboundary_line\x18\x03 \x03(\x0b\x32 .osi3.LaneBoundary.BoundaryPoint\x12<\n\x12\x62oundary_line_rmse\x18\x04 \x03(\x0b\x32 .osi3.LaneBoundary.BoundaryPoint\x12!\n\x19\x62oundary_line_confidences\x18\x05 \x03(\x01\x12\x31\n\x11\x63olor_description\x18\x06 \x01(\x0b\x32\x16.osi3.ColorDescription\x1ag\n\x15\x43\x61ndidateLaneBoundary\x12\x13\n\x0bprobability\x18\x01 \x01(\x01\x12\x39\n\x0e\x63lassification\x18\x02 \x01(\x0b\x32!.osi3.LaneBoundary.ClassificationB\x02H\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osi3.osi_detectedlane_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\001'
  _globals['_DETECTEDLANE']._serialized_start=113
  _globals['_DETECTEDLANE']._serialized_end=311
  _globals['_DETECTEDLANE_CANDIDATELANE']._serialized_start=224
  _globals['_DETECTEDLANE_CANDIDATELANE']._serialized_end=311
  _globals['_DETECTEDLANEBOUNDARY']._serialized_start=314
  _globals['_DETECTEDLANEBOUNDARY']._serialized_end=757
  _globals['_DETECTEDLANEBOUNDARY_CANDIDATELANEBOUNDARY']._serialized_start=654
  _globals['_DETECTEDLANEBOUNDARY_CANDIDATELANEBOUNDARY']._serialized_end=757
# @@protoc_insertion_point(module_scope)
