# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: osi3/osi_detectedroadmarking.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'osi3/osi_detectedroadmarking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from osi3 import osi_common_pb2 as osi3_dot_osi__common__pb2
from osi3 import osi_roadmarking_pb2 as osi3_dot_osi__roadmarking__pb2
from osi3 import osi_detectedobject_pb2 as osi3_dot_osi__detectedobject__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"osi3/osi_detectedroadmarking.proto\x12\x04osi3\x1a\x15osi3/osi_common.proto\x1a\x1aosi3/osi_roadmarking.proto\x1a\x1dosi3/osi_detectedobject.proto\"\xe9\x02\n\x13\x44\x65tectedRoadMarking\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.osi3.DetectedItemHeader\x12\"\n\x04\x62\x61se\x18\x02 \x01(\x0b\x32\x14.osi3.BaseStationary\x12\'\n\tbase_rmse\x18\x03 \x01(\x0b\x32\x14.osi3.BaseStationary\x12\x41\n\tcandidate\x18\x04 \x03(\x0b\x32..osi3.DetectedRoadMarking.CandidateRoadMarking\x12\x31\n\x11\x63olor_description\x18\x05 \x01(\x0b\x32\x16.osi3.ColorDescription\x1a\x65\n\x14\x43\x61ndidateRoadMarking\x12\x13\n\x0bprobability\x18\x01 \x01(\x01\x12\x38\n\x0e\x63lassification\x18\x02 \x01(\x0b\x32 .osi3.RoadMarking.ClassificationB\x02H\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osi3.osi_detectedroadmarking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\001'
  _globals['_DETECTEDROADMARKING']._serialized_start=127
  _globals['_DETECTEDROADMARKING']._serialized_end=488
  _globals['_DETECTEDROADMARKING_CANDIDATEROADMARKING']._serialized_start=387
  _globals['_DETECTEDROADMARKING_CANDIDATEROADMARKING']._serialized_end=488
# @@protoc_insertion_point(module_scope)
