# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: osi3/osi_detectedoccupant.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'osi3/osi_detectedoccupant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from osi3 import osi_occupant_pb2 as osi3_dot_osi__occupant__pb2
from osi3 import osi_detectedobject_pb2 as osi3_dot_osi__detectedobject__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fosi3/osi_detectedoccupant.proto\x12\x04osi3\x1a\x17osi3/osi_occupant.proto\x1a\x1dosi3/osi_detectedobject.proto\"\xda\x01\n\x10\x44\x65tectedOccupant\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.osi3.DetectedItemHeader\x12;\n\tcandidate\x18\x02 \x03(\x0b\x32(.osi3.DetectedOccupant.CandidateOccupant\x1a_\n\x11\x43\x61ndidateOccupant\x12\x13\n\x0bprobability\x18\x01 \x01(\x01\x12\x35\n\x0e\x63lassification\x18\x02 \x01(\x0b\x32\x1d.osi3.Occupant.ClassificationB\x02H\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osi3.osi_detectedoccupant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\001'
  _globals['_DETECTEDOCCUPANT']._serialized_start=98
  _globals['_DETECTEDOCCUPANT']._serialized_end=316
  _globals['_DETECTEDOCCUPANT_CANDIDATEOCCUPANT']._serialized_start=221
  _globals['_DETECTEDOCCUPANT_CANDIDATEOCCUPANT']._serialized_end=316
# @@protoc_insertion_point(module_scope)
