# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: osi3/osi_datarecording.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'osi3/osi_datarecording.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from osi3 import osi_sensordata_pb2 as osi3_dot_osi__sensordata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cosi3/osi_datarecording.proto\x12\x04osi3\x1a\x19osi3/osi_sensordata.proto\"9\n\x10SensorDataSeries\x12%\n\x0bsensor_data\x18\x01 \x03(\x0b\x32\x10.osi3.SensorData\">\n\x14SensorDataSeriesList\x12&\n\x06sensor\x18\x01 \x03(\x0b\x32\x16.osi3.SensorDataSeriesB\x02H\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osi3.osi_datarecording_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\001'
  _globals['_SENSORDATASERIES']._serialized_start=65
  _globals['_SENSORDATASERIES']._serialized_end=122
  _globals['_SENSORDATASERIESLIST']._serialized_start=124
  _globals['_SENSORDATASERIESLIST']._serialized_end=186
# @@protoc_insertion_point(module_scope)
