# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: osi3/osi_sensorspecific.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'osi3/osi_sensorspecific.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from osi3 import osi_common_pb2 as osi3_dot_osi__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dosi3/osi_sensorspecific.proto\x12\x04osi3\x1a\x15osi3/osi_common.proto\"&\n\x17RadarSpecificObjectData\x12\x0b\n\x03rcs\x18\x01 \x01(\x01\"\x19\n\x17LidarSpecificObjectData\"\x1a\n\x18\x43\x61meraSpecificObjectData\"\xc3\x05\n\x1cUltrasonicSpecificObjectData\x12+\n#maximum_measurement_distance_sensor\x18\x01 \x01(\x01\x12\x13\n\x0bprobability\x18\x02 \x01(\x01\x12T\n\x14trilateration_status\x18\x03 \x01(\x0e\x32\x36.osi3.UltrasonicSpecificObjectData.TrilaterationStatus\x12\x37\n\x05trend\x18\x04 \x01(\x0e\x32(.osi3.UltrasonicSpecificObjectData.Trend\x12?\n\tsignalway\x18\x05 \x03(\x0b\x32,.osi3.UltrasonicSpecificObjectData.Signalway\x1aW\n\tSignalway\x12#\n\tsender_id\x18\x01 \x01(\x0b\x32\x10.osi3.Identifier\x12%\n\x0breceiver_id\x18\x02 \x01(\x0b\x32\x10.osi3.Identifier\"\xa9\x01\n\x13TrilaterationStatus\x12 \n\x1cTRILATERATION_STATUS_UNKNOWN\x10\x00\x12\x1e\n\x1aTRILATERATION_STATUS_OTHER\x10\x01\x12)\n%TRILATERATION_STATUS_NOT_TRILATERATED\x10\x02\x12%\n!TRILATERATION_STATUS_TRILATERATED\x10\x03\"\x8b\x01\n\x05Trend\x12\x11\n\rTREND_UNKNOWN\x10\x00\x12\x0f\n\x0bTREND_OTHER\x10\x01\x12\x1e\n\x1aTREND_CONSTANT_APPROACHING\x10\x02\x12\x12\n\x0eTREND_CONSTANT\x10\x03\x12\x15\n\x11TREND_APPROACHING\x10\x04\x12\x13\n\x0fTREND_DEPARTING\x10\x05\x42\x02H\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osi3.osi_sensorspecific_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\001'
  _globals['_RADARSPECIFICOBJECTDATA']._serialized_start=62
  _globals['_RADARSPECIFICOBJECTDATA']._serialized_end=100
  _globals['_LIDARSPECIFICOBJECTDATA']._serialized_start=102
  _globals['_LIDARSPECIFICOBJECTDATA']._serialized_end=127
  _globals['_CAMERASPECIFICOBJECTDATA']._serialized_start=129
  _globals['_CAMERASPECIFICOBJECTDATA']._serialized_end=155
  _globals['_ULTRASONICSPECIFICOBJECTDATA']._serialized_start=158
  _globals['_ULTRASONICSPECIFICOBJECTDATA']._serialized_end=865
  _globals['_ULTRASONICSPECIFICOBJECTDATA_SIGNALWAY']._serialized_start=464
  _globals['_ULTRASONICSPECIFICOBJECTDATA_SIGNALWAY']._serialized_end=551
  _globals['_ULTRASONICSPECIFICOBJECTDATA_TRILATERATIONSTATUS']._serialized_start=554
  _globals['_ULTRASONICSPECIFICOBJECTDATA_TRILATERATIONSTATUS']._serialized_end=723
  _globals['_ULTRASONICSPECIFICOBJECTDATA_TREND']._serialized_start=726
  _globals['_ULTRASONICSPECIFICOBJECTDATA_TREND']._serialized_end=865
# @@protoc_insertion_point(module_scope)
